### PR TITLE
improve: skip local vtep when generate vxlan fdb entry

### PR DESCRIPTION
**Pull request by gaozhengwei**
Pull Request Description
---

### Special notes for reviews

### CODE REVIEW

**Review by hhyasdf — APPROVED** [review]
Good job!

Could you please sign the CLA to make it mergable?

**Comment by gaozhengwei** [comment]
> Good job!
> 
> Could you please sign the CLA to make it mergable?

Done

**Comment by hhyasdf** [comment]
@gaozhengwei The commits need to be signed either :), could you please use `git commit -S --amend` to sign it?

**Comment by gaozhengwei** [comment]
> @gaozhengwei The commits need to be signed either :), could you please use `git commit -S --amend` to sign it?

Thanks,  I  had done

**Review by hhyasdf — APPROVED** [review]

**Comment by gaozhengwei** [comment]
> > > @gaozhengwei The commits need to be signed either :), could you please use `git commit -S --amend` to sign it?
> > 
> > 
> > Thanks, I had done
> 
> Seems not :(.
ok， please recheck

**Review by hhyasdf — APPROVED** [review]

**Comment by hhyasdf** [comment]
@gaozhengwei, thanks for your contribution!

**Pull request merged**
