### PR TITLE
remove checks for kubernetes service

### PR DESCRIPTION
**Pull request by hhyasdf**
Pull Request Description
---

### Describe what this PR does / why we need it
The kubernetes svc check commands in policy.sh cannot work in a ipv6 only environment. Just remove it.

### Special notes for reviews

### CODE REVIEW

**Review by mars1024 — COMMENTED** [review]
what's ipv6 only environment?

**Comment by hhyasdf** [comment]
> 

Only ipv6 address on node, but pods will be DualStack.

**Comment by hhyasdf** [comment]
> what's ipv6 only environment?

Only ipv6 address on node, but pods will be DualStack.

**Review by mars1024 — APPROVED** [review]
/lgtm

**Pull request merged**
